name: Debug Workflow


on:
  workflow_dispatch:


jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Preview Release
        run: ./build.cmd DebugTask --nuget-api-key "${{ secrets.TEST_API_KEY }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
