name: ✅No GitHub Release Status Check


on:
  workflow_dispatch:
#  pull_request:
#    branches:
#      - 'master'
#      - 'release/v*.*.*'


# TODO: Needs to run on windows and ubuntu
jobs:
  build_project:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run No GitHub Release Status Check
        run: ./build.cmd NoGitHubReleaseStatusCheck
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
