name: ✅Preview Feature PR Status Check


on:
  workflow_dispatch: # Add manual inputs or remove
  pull_request:
    branches:
      - release/v*.*.*-preview.*

# TODO: Needs to run on windows and ubuntu

jobs:
  build_project:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Feature PR Status Check
        run: ./build.cmd PreviewFeaturePRStatusCheck
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
