name: ✅Preview Release PR Status Check


on:
  workflow_dispatch:
  pull_request:
    branches:
      - release/v*.*.*


jobs:
  build_project:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Preview Release PR Status Check
        run: ./build.cmd PrevReleasePRStatusCheck
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
