name: ✅Production Release PR Status Check


on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - master


jobs:
  build_project:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Production Release PR Status Check
        run: ./build.cmd ProdReleasePRStatusCheck
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
